version: "3"

networks:
    inception:
        name: inception

volumes:
    wordpress_volume:
        name: wordpress_volume
        driver_opts:
            o: bind
            type: none
            device: /home/danbarbo/data/wordpress

    mariadb_volume:
        name: mariadb_volume
        driver_opts:
            o: bind
            type: none
            device: /home/danbarbo/data/mariadb

services:
    mariadb:
        image: mariadb
        container_name: mariadb
        env_file:
            - .env
        environment:
            - ADMIN_NAME
            - ADMIN_PASSWORD
            - DB_NAME
        build:
            context: requirements/mariadb
        volumes:
            - mariadb_volume:/var/lib/mysql
        networks:
            - inception
        expose:
            - 3306
        restart: on-failure

    wordpress:
        depends_on:
            - mariadb
            - redis
        image: wordpress
        container_name: wordpress
        env_file:
            - .env
        environment:
            - TITLE
            - DOMAIN
            - DB_NAME
            - ADMIN_NAME
            - ADMIN_EMAIL
            - ADMIN_PASSWORD
            - USER_NAME
            - USER_EMAIL
            - USER_PASSWORD
            - DB_USER
            - DB_PASSWORD
            - DB_HOST
            - REDIS_HOST
            - REDIS_PORT
        build:
            context: requirements/wordpress
        volumes:
            - wordpress_volume:/var/www/html
        networks:
            - inception
        expose:
            - 9000
        restart: on-failure

    nginx:
        depends_on:
            - wordpress
            - mariadb
        image: nginx
        container_name: nginx
        build:
            context: requirements/nginx
        ports:
            - 443:443
        volumes:
            - wordpress_volume:/var/www/html
        networks:
            - inception
        restart: on-failure

    redis:
        image: redis
        container_name: redis
        networks:
            - inception
        build:
            context: requirements/bonus/redis
        expose:
            - 6379
        restart: on-failure

    ftp:
        depends_on:
            - wordpress
        image: ftp
        container_name: ftp
        env_file:
            - .env
        build:
            context: requirements/bonus/ftp
        environment:
            - FTP_USER
            - FTP_PASSWORD
        ports:
            - 0.0.0.0:21:21
            - 0.0.0.0:40000-40005:40000-40005
        networks:
            - inception
        volumes:
            - wordpress_volume:/var/www/html
        restart: on-failure

    website:
        image: website
        container_name: website
        build:
            context: requirements/bonus/website
        ports:
            - "8080:8080"
        networks:
            - inception
        restart: on-failure
